### ISSUE TITLE
S3 Relay for Mongoid

### ISSUE THREAD

**Issue by hartator** [kjohnston/s3_relay#17]
Not really an issue, and thanks for the awesome work done in `s3_relay`.

I've ported your Gem to support a MongoDB wrapper, Mongoid: https://github.com/hartator/mongoid-direct-s3-upload

Do you want me to make changes concerning the wording referring back to this repository?

I've done a few modifications not directly related to the Mongoid port. Notably the addition of an helper to get the S3 url with the signature part. (ie. `logo_upload.public_url`) And, I don't know if it's on purpose or an overlook, but when dealing with one attachment, it was returning the least recent one, in opposition of the most recent one (`.last`using DESC on pending_at will return the very first upload).

Refs:
- https://github.com/hartator/mongoid-direct-s3-upload/blob/729aedef901c8ff1f833c19b72d21a8d87143ac7/lib/s3_relay/private_url.rb#L16
- https://github.com/hartator/mongoid-direct-s3-upload/commit/0af3f8a6d7f6aae151f832fef3167d53d0280513

Maybe, we can backport these two changes to the original Gem.

**Comment by kjohnston** [comment]
@hartator sorry for the much delayed response.  I don't have any plans to support MongoDB, so forking is the right way to go.  Thanks for linking back to this project (the link actually seems to point to the wrong place at the moment though).

The line you commented on should probably be changed, pull requests are welcome : )  Since it is under the `has_one` relationship though I believe the expectation is that there would only in reality be one result which is why the issue hasn't surfaced before, but it may be that my ☕️ hasn't kicked in yet.
