### ISSUE TITLE
File upload is tied to parent record

### ISSUE THREAD

**Issue by andypandy** [kjohnston/s3_relay#8]
Per @bousquet we want the ability to decouple the upload from a particular parent record, and per @kjohnston we want uploads tied to the user. Would it be fine to decouple from both, and then use the javascript API to POST whatever data to whatever endpoint you want?

**Questions:**
-Is this configured in Rails or in the JS? In the template tag/helper?
-For backwards compatibility it seems like it will need to notify parent as default. Could we have maybe 3 options: `parent`, `user`, `none`?

**Comment by bousquet** [comment]
@kjohnston we can definitely pass the `user_id` in but I could see where using the given `user_id` gives the client submitted parameters too much trust (in case that value was changed).  Is there a good place to hook authentication into the submission endpoint so that your receiver of the "file uploaded" POST can capture the session details (and use that to determine the session's `user_id`) before handing it to the processor job that is enqueued to finish handle the file?

**Comment by kjohnston** [comment]
@bousquet, that was @andypandy, but I agree with you, the gem needs to leverage the Rails app's authentication to assign the user_id, we can't trust a user_id included in the POST.

The gem allows you to enforce that the user be authenticated, see the part about `authenticate_for_s3_relay` in the readme.  The gem tries to be unassuming that a given authentication library is being used, but this method should always be used.  Ideally we'd make it so users can't miss this, otherwise the app will be wide open to presigning requests and upload persistence.  

The `uploads#create` endpoint receives the POST to consume the S3 URL.  The `upload_attrs` there needs to include the `user_id: current_user.id`, or similar.  If we want to plan for authentication libraries that don't define a `current_user` method, we could offer a another method similar to `authenticate_for_s3_relay` where you could define the actual way you access your user object.

I'm open to the idea of eliminating the "parent" relationship.  The pattern @djohnson is working on is a better version of where I've headed with the implementation the last couple of times - 1) just get the upload persisted, 2) hit an endpoint in your app to persist the parent object, 3) enqueue a job for the parent to consume the upload and mark it uploaded.  With this strategy, we could eliminate the polymorphic parent type and ID params and the callback from S3Relay::Upload to the parent's optional `#notify_parent` method.

**Comment by djohnson** [comment]
I think the current implementation of user handling isn't bad with the only change being as @kjohnston said add a way to support more then `current_user`.  It has to be on the controller level for the reasons previously mentioned.  It really seems like we need a good way to enable overriding pieces of the controller.

As for the parent record I think it would be best if it was just made optional. If it's not set or the parent doesn't define the `import_upload` then it just gets stored in the upload table and no callbacks fire.
